--CREATE TABLE student_calendar(
--    id INT AUTO_INCREMENT PRIMARY KEY,
--    name VARCHAR(255) NOT NULL,
--    start_time TIMESTAMP NOT NULL,
--    end_time TIMESTAMP NOT NULL,
--    id_teacher VARCHAR(10) NOT NULL,
--    created_by VARCHAR(255),
--    created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--    modified_by VARCHAR(255),
--    modified_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
--);