ALTER TABLE teacher_calendar
ADD COLUMN course_id BIGINT,
ADD COLUMN chapter_id BIGINT,
ADD COLUMN user_id BINARY(16),
ADD COLUMN status ENUM('FREE', 'BOOKED', 'CANCELLED') NOT NULL DEFAULT 'FREE',
ADD CONSTRAINT
  FOREIGN KEY (user_id) REFERENCES tbl_user(id);