ALTER TABLE teacher_calendar
ADD COLUMN user_id BINARY(16),
ADD COLUMN status ENUM('FREE', 'BOOKED', 'CANCELLED', 'BUSY') NOT NULL DEFAULT 'FREE',
ADD CONSTRAINT
  FOREIGN KEY (user_id) REFERENCES tbl_user(id);